<?php

namespace Gde\Bundle\PlaylearnFrontendBundle\Entity;

use Doctrine\ORM\EntityRepository;

/**
 * questionRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class questionRepository extends EntityRepository
{

    public function findLastQuestion()
    {
        $qb = $this->createQueryBuilder('q')
            ->select()
            ->where('q.response IS NULL');


        return $qb->getFirstResult();

    }

}
